// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("filter")
	ScopeName = "github.com/nicolastakashi/ntakashi-opentelemetry-collector/processor/unusedmetricprocessor"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
