// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/nicolastakashi/ntakashi-opentelemetry-collector/processor/unusedmetricprocessor")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/nicolastakashi/ntakashi-opentelemetry-collector/processor/unusedmetricprocessor")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                         metric.Meter
	mu                                            sync.Mutex
	registrations                                 []metric.Registration
	OtelcolProcessorUnusedmetricBackendDuration   metric.Int64Histogram
	OtelcolProcessorUnusedmetricDropped           metric.Int64Counter
	OtelcolProcessorUnusedmetricDroppedDatapoints metric.Int64UpDownCounter
	OtelcolProcessorUnusedmetricError             metric.Int64Counter
	OtelcolProcessorUnusedmetricKept              metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.OtelcolProcessorUnusedmetricBackendDuration, err = builder.meter.Int64Histogram(
		"otelcol_otelcol_processor_unusedmetric_backend_duration",
		metric.WithDescription("The duration of the backend call to the unusedmetric backend"),
		metric.WithUnit("s"),
	)
	errs = errors.Join(errs, err)
	builder.OtelcolProcessorUnusedmetricDropped, err = builder.meter.Int64Counter(
		"otelcol_otelcol_processor_unusedmetric_dropped",
		metric.WithDescription("The number of metrics dropped by the unusedmetric processor"),
		metric.WithUnit("{metrics}"),
	)
	errs = errors.Join(errs, err)
	builder.OtelcolProcessorUnusedmetricDroppedDatapoints, err = builder.meter.Int64UpDownCounter(
		"otelcol_otelcol_processor_unusedmetric_dropped_datapoints",
		metric.WithDescription("The number of datapoints dropped by the unusedmetric processor"),
		metric.WithUnit("{datapoints}"),
	)
	errs = errors.Join(errs, err)
	builder.OtelcolProcessorUnusedmetricError, err = builder.meter.Int64Counter(
		"otelcol_otelcol_processor_unusedmetric_error",
		metric.WithDescription("The number of errors returned by the unusedmetric processor"),
		metric.WithUnit("{errors}"),
	)
	errs = errors.Join(errs, err)
	builder.OtelcolProcessorUnusedmetricKept, err = builder.meter.Int64Counter(
		"otelcol_otelcol_processor_unusedmetric_kept",
		metric.WithDescription("The number of metrics kept by the unusedmetric processor"),
		metric.WithUnit("{metrics}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
